language:       node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
script:
  - npm run build
env:
  global:
      - secure:     nOkN0QT3Ikm1gPXknJ3Dswd9FBwwrz/TCrOdFqpXuBK7JWNdjrG4VbSB8NWC4x52+1sF0lo6mIFRHNdSfazWB+4IkXvoYirMoqVmw+9iLMy7jv2mwmivgPkCb5EOmeKhhzDvS4BvV48qsmuPynbUKOcxHlF2MzKasZJvitXb6pQBEbrSrgCKJ4A+OUIapMGaUVLouBFfOViyU23WA8I8NviGneIwy4lDTIKr5qkhqX5peW1dOM9zsq48m4NcPdpLxuZ9ni1r0gMwNSP4lkgVD0EbPSbvZPIZt03CEfildOXkYnTfI1YNxFugMoYxwXay5a9Oz6hQbdmipbhLYVZyGCJukDOgkxC82g6TvBKrobJJKoJAFSg62bosc/608ZSscU65Bz118VrBd9JhRbBTnXulYZN6a488NrACANYEcv7t/qFS6ssmG3MiaNki4unzrD2t/u8mWJJndnN0N4V7U20F8yldJM+iwaCZPEm/y9T5TUArJRPzdly2ldxP9N90GjefKhpGO4sOBG8A51ZPUnVDIQsTC2p6OqI25Af+sMpXbjrVdU7w45cNmDpKMXlFFXsQ/Drc8qy21cm4/GLE0XJ3NCgB2xKZiAUNUfmPLRJixoez3RhGvyGfBrm/q9DZ/gcMbPClswg1IHS37m65/sHE2o3njlvvQ0Y3GYUoOS8=
      - secure:     dDG4TRibVPslxslxUr2OViStbIGVmsmTGMOabb67hLet2MShP/P05ihGJAP4HM2quNm+PjkWn0UvdFR41HBQPlwT++TQkQAogeXBRp8fBh7RV2fHldOgFTfUvb8ISZgC6iNP74+f5yzgHN59dP8a2YGLPgVF3ZhoBDv+y6SZ5a+RjEZnrS+B5KZlKJcLolId5+2HHLts/m4pOYFtAIqI0IskEdbHRUUMbz49tRk4YUXaI+M97UTAmKcGlM3yv7kwabBKZY4sfOt6z7FZDgOWOkAhss06GTO2TOultweUAiFL6MsxYNvEVnPo0NsyHZlioAhRbj7+amq3D340FFg1XWWUuxvniBlvBgdPvB7BTKWIeodGvUIRS1dpgQCm7OvG5rrcY/88/QzCOWR+XGZXrUmmfWLBI7pAoKSeHJXW+lxJr4C40Ozp+zJ84uDN8HAB6kHEW6MCn/GIGfYwR6pqmcjTA5NC/pPwaIjzG/yKFhJv/cVm9ok386Tf3hjU8iT+mwr2AtXMVCS2UO/wDuRaSVs+4wTWhXUBGAM+Rt7y0UWU+D35ez2z8Sc+ffg6veQesoW8G5d4+wIa7DPXeF6XNMbo824rcBbCeOOyGUTjIw0NOcpi7tex0YPU0bNRXMhG2Go6FayyB8BWCCPi6aVgvV2yky9jtRGyZ+nVbREA2xo=
after_success:
    "zip -r build.zip build"
    "curl --ftp-create-dirs -T build.zip -u $FTPUSER:$FTPPASS ftp://vattrack.org/build.zip"
